### ISSUE TITLE
Missing database.yml file in config

### ISSUE THREAD

**Issue by mehdi514** [akshaymohite/rails-react-crud-app#11]
https://rubyinrails.com/2019/11/19/rails-react-js-application-with-crud-operation/
I followed your above tutorial but it just render hello-world.jsx on every posts route, either it's new or edit.
There is also not a database.yml file in your config folder.

**Comment by akshaymohite** [comment]
@mehdi514 

> There is also not a database.yml file in your config folder.

`database.yml` is not kept in VCS deliberately, you can use database config of your own choice. Although, I will be adding a sample database configuration file in the repository soon.

> I followed your above tutorial but it just render hello-world.jsx on every posts route, either it's new or edit.

Could you please share more (code) details or the link to repository where I can observe and debug the issue?
